import { registerContracts } from '@oppsera/core/events/contracts';
import {
  OrderOpenedDataSchema,
  OrderLineAddedDataSchema,
  OrderLineRemovedDataSchema,
  OrderServiceChargeAddedDataSchema,
  OrderServiceChargeRemovedDataSchema,
  OrderDiscountAppliedDataSchema,
  OrderPlacedDataSchema,
  OrderPaidDataSchema,
  OrderUpdatedDataSchema,
  OrderVoidedDataSchema,
  OrderClonedDataSchema,
  OrderReopenedDataSchema,
  OrderDeletedDataSchema,
  OrderHeldDataSchema,
  OrderRecalledDataSchema,
} from './types';

registerContracts({
  moduleName: 'orders',
  emits: [
    { eventType: 'order.opened.v1', dataSchema: OrderOpenedDataSchema },
    { eventType: 'order.line_added.v1', dataSchema: OrderLineAddedDataSchema },
    { eventType: 'order.line_removed.v1', dataSchema: OrderLineRemovedDataSchema },
    { eventType: 'order.service_charge_added.v1', dataSchema: OrderServiceChargeAddedDataSchema },
    { eventType: 'order.service_charge_removed.v1', dataSchema: OrderServiceChargeRemovedDataSchema },
    { eventType: 'order.discount_applied.v1', dataSchema: OrderDiscountAppliedDataSchema },
    { eventType: 'order.placed.v1', dataSchema: OrderPlacedDataSchema },
    { eventType: 'order.paid.v1', dataSchema: OrderPaidDataSchema },
    { eventType: 'order.updated.v1', dataSchema: OrderUpdatedDataSchema },
    { eventType: 'order.voided.v1', dataSchema: OrderVoidedDataSchema },
    { eventType: 'order.cloned.v1', dataSchema: OrderClonedDataSchema },
    { eventType: 'order.reopened.v1', dataSchema: OrderReopenedDataSchema },
    { eventType: 'order.deleted.v1', dataSchema: OrderDeletedDataSchema },
    { eventType: 'order.held.v1', dataSchema: OrderHeldDataSchema },
    { eventType: 'order.recalled.v1', dataSchema: OrderRecalledDataSchema },
  ],
  consumes: [],
});
