/**
 * Data pool helpers for load testing.
 *
 * Provides tenant-scoped test data: customer IDs, item IDs,
 * order IDs, and weighted random selection.
 */

import { SharedArray } from 'k6/data';

// Load seed data pools (generated by seed script)
const dataPool = new SharedArray('data-pool', function () {
  const path = __ENV.DATA_POOL_PATH || './seed-manifest.json';
  try {
    return [JSON.parse(open(path))];
  } catch (e) {
    console.warn(`Data pool not found at ${path}`);
    return [{ tenantItems: {}, tenantCustomers: {}, tenantOrders: {} }];
  }
});

const pool = dataPool[0];

/**
 * Get a random customer ID for a tenant.
 * @param {number} tenantIndex
 * @returns {string|null}
 */
export function getRandomCustomerId(tenantIndex) {
  const key = `T${String(tenantIndex).padStart(2, '0')}`;
  const customers = pool.tenantCustomers?.[key] || [];
  if (customers.length === 0) return null;
  return customers[Math.floor(Math.random() * customers.length)].customerId;
}

/**
 * Get a random item for a tenant (for POS checkout).
 * @param {number} tenantIndex
 * @returns {Object|null} { catalogItemId, sku, name }
 */
export function getRandomItem(tenantIndex) {
  const key = `T${String(tenantIndex).padStart(2, '0')}`;
  const items = pool.tenantItems?.[key] || [];
  if (items.length === 0) return null;
  return items[Math.floor(Math.random() * items.length)];
}

/**
 * Get a random placed order ID for a tenant (for history/detail lookups).
 * @param {number} tenantIndex
 * @returns {string|null}
 */
export function getRandomOrderId(tenantIndex) {
  const key = `T${String(tenantIndex).padStart(2, '0')}`;
  const orders = pool.tenantOrders?.[key] || [];
  if (orders.length === 0) return null;
  return orders[Math.floor(Math.random() * orders.length)].orderId;
}

/**
 * Weighted random selection from an array.
 * Items with higher weight are selected proportionally more often.
 *
 * @param {Array<{ item: any, weight: number }>} weighted
 * @returns {any} Selected item
 */
export function weightedRandom(weighted) {
  const totalWeight = weighted.reduce((sum, w) => sum + w.weight, 0);
  let r = Math.random() * totalWeight;
  for (const { item, weight } of weighted) {
    r -= weight;
    if (r <= 0) return item;
  }
  return weighted[weighted.length - 1].item;
}

/**
 * Generate a random business date (today or yesterday).
 * @returns {string} ISO date string (YYYY-MM-DD)
 */
export function getBusinessDate() {
  const today = new Date();
  // 80% today, 20% yesterday
  if (Math.random() > 0.2) {
    return today.toISOString().slice(0, 10);
  }
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  return yesterday.toISOString().slice(0, 10);
}

/**
 * Generate a random search query from common patterns.
 * @param {number} tenantIndex
 * @returns {string}
 */
export function getSearchQuery(tenantIndex) {
  const pad = String(tenantIndex).padStart(2, '0');
  const queries = [
    `Tenant${pad}`,
    `Customer`,
    `T${pad}_SKU`,
    `user_${Math.floor(Math.random() * 100)}@tenant_${pad}`,
    'john',
    'coffee',
    'burger',
  ];
  return queries[Math.floor(Math.random() * queries.length)];
}
