import { eq, and } from 'drizzle-orm';
import type { RequestContext } from '@oppsera/core/auth/context';
import {
  db,
  aiAssistantFeedback,
  aiAssistantMessages,
  aiAssistantThreads,
} from '@oppsera/db';
import { NotFoundError } from '@oppsera/shared';
import type { SubmitFeedbackInput } from '../types';

export async function submitFeedback(
  ctx: RequestContext,
  input: SubmitFeedbackInput,
): Promise<{ id: string; rating: string }> {
  const { messageId, rating, reasonCode, freeformComment } = input;

  // Verify the message belongs to this tenant before inserting feedback
  const [msg] = await db
    .select({ id: aiAssistantMessages.id })
    .from(aiAssistantMessages)
    .where(
      and(
        eq(aiAssistantMessages.id, messageId),
        eq(aiAssistantMessages.tenantId, ctx.tenantId),
      ),
    )
    .limit(1);

  if (!msg) {
    throw new NotFoundError('Message', messageId);
  }

  // Insert feedback record (id is auto-generated by $defaultFn)
  const [feedback] = await db
    .insert(aiAssistantFeedback)
    .values({
      tenantId: ctx.tenantId,
      messageId,
      userId: ctx.user.id,
      rating,
      reasonCode: reasonCode ?? null,
      freeformComment: freeformComment ?? null,
    })
    .returning();

  // Update message feedback status
  await db
    .update(aiAssistantMessages)
    .set({ feedbackStatus: rating })
    .where(
      and(
        eq(aiAssistantMessages.id, messageId),
        eq(aiAssistantMessages.tenantId, ctx.tenantId),
      ),
    );

  // Auto-flag thread on thumbs-down
  if (rating === 'down') {
    const msgs = await db
      .select({ threadId: aiAssistantMessages.threadId })
      .from(aiAssistantMessages)
      .where(eq(aiAssistantMessages.id, messageId))
      .limit(1);

    if (msgs[0]) {
      await db
        .update(aiAssistantThreads)
        .set({ status: 'flagged', updatedAt: new Date() })
        .where(
          and(
            eq(aiAssistantThreads.id, msgs[0].threadId),
            eq(aiAssistantThreads.tenantId, ctx.tenantId),
          ),
        );
    }
  }

  return { id: feedback!.id, rating };
}
