/**
 * JWT pool loader for multi-tenant load testing.
 *
 * Reads auth-tokens.json (generated by seed script) into a SharedArray
 * for memory-efficient sharing across VUs.
 *
 * Token file format:
 * {
 *   "tenants": [
 *     {
 *       "tenantId": "...",
 *       "tenantIndex": 1,
 *       "tenantSize": "large",
 *       "locationIds": ["loc1", "loc2"],
 *       "users": [
 *         { "userId": "...", "email": "...", "jwt": "...", "role": "owner" },
 *         { "userId": "...", "email": "...", "jwt": "...", "role": "cashier" }
 *       ]
 *     }
 *   ]
 * }
 */

import { SharedArray } from 'k6/data';

// Load tokens once, shared across all VUs (memory efficient)
const tokenData = new SharedArray('auth-tokens', function () {
  const path = __ENV.AUTH_TOKENS_PATH || './auth-tokens.json';
  try {
    return [JSON.parse(open(path))];
  } catch (e) {
    console.error(`Failed to load auth tokens from ${path}: ${e.message}`);
    console.error('Run seed script first: npx tsx scripts/seed-load-test.ts --profile stage1');
    return [{ tenants: [] }];
  }
});

const data = tokenData[0];

/**
 * Get auth headers + context for a specific tenant by index (1-based).
 * @param {number} tenantIndex - 1-based tenant index
 * @param {string} [role='cashier'] - Role to select (owner, manager, cashier, etc.)
 * @returns {{ tenantId, tenantIndex, userId, jwt, locationId, locationIds, headers }}
 */
export function getAuthForTenant(tenantIndex, role = 'cashier') {
  const tenant = data.tenants.find((t) => t.tenantIndex === tenantIndex);
  if (!tenant) {
    throw new Error(`No tenant with index ${tenantIndex}. Available: ${data.tenants.map((t) => t.tenantIndex).join(', ')}`);
  }

  const user = tenant.users.find((u) => u.role === role) || tenant.users[0];
  if (!user) {
    throw new Error(`No user with role '${role}' for tenant ${tenantIndex}`);
  }

  const locationId = tenant.locationIds[0];

  return {
    tenantId: tenant.tenantId,
    tenantIndex: tenant.tenantIndex,
    tenantSize: tenant.tenantSize,
    userId: user.userId,
    jwt: user.jwt,
    locationId,
    locationIds: tenant.locationIds,
    headers: {
      Authorization: `Bearer ${user.jwt}`,
      'Content-Type': 'application/json',
      'X-Location-Id': locationId,
    },
  };
}

/**
 * Deterministic tenant assignment for a VU, weighted by tenant size.
 * Large tenants get more VUs than small tenants.
 * @param {number} vuId - k6 __VU (1-based)
 * @returns {{ tenantId, tenantIndex, userId, jwt, locationId, locationIds, headers }}
 */
export function getAuthForVU(vuId) {
  if (data.tenants.length === 0) {
    throw new Error('No tenants loaded. Run seed script first.');
  }

  // Build weighted list: large=5x, medium=2x, small=1x
  const weights = { large: 5, medium: 2, small: 1 };
  const weightedList = [];
  for (const tenant of data.tenants) {
    const w = weights[tenant.tenantSize] || 1;
    for (let i = 0; i < w; i++) {
      weightedList.push(tenant.tenantIndex);
    }
  }

  const tenantIndex = weightedList[(vuId - 1) % weightedList.length];
  return getAuthForTenant(tenantIndex, 'cashier');
}

/**
 * Get all tenant indexes for isolation testing.
 * @returns {number[]}
 */
export function getAllTenantIndexes() {
  return data.tenants.map((t) => t.tenantIndex);
}

/**
 * Get tenant count.
 * @returns {number}
 */
export function getTenantCount() {
  return data.tenants.length;
}
