import type { MetricDef, DimensionDef, MetricDimensionRelation, LensDef } from './types';

// ── Core Dimensions ───────────────────────────────────────────────

export const CORE_DIMENSIONS: Omit<DimensionDef, 'isActive'>[] = [
  {
    slug: 'date',
    displayName: 'Date',
    description: 'Business date of the transaction',
    domain: 'core',
    category: 'time',
    sqlExpression: 'business_date',
    sqlTable: 'rm_daily_sales',
    sqlDataType: 'date',
    isTimeDimension: true,
    timeGranularities: ['day', 'week', 'month', 'quarter', 'year'],
    aliases: ['day', 'when', 'period', 'time', 'business date'],
    examplePhrases: ['today', 'yesterday', 'last week', 'last month', 'this year'],
  },
  {
    slug: 'location',
    displayName: 'Location',
    description: 'Store or outlet location',
    domain: 'core',
    category: 'geography',
    sqlExpression: 'location_id',
    sqlTable: 'rm_daily_sales',
    sqlDataType: 'text',
    isTimeDimension: false,
    lookupTable: 'locations',
    lookupKeyColumn: 'id',
    lookupLabelColumn: 'name',
    aliases: ['store', 'outlet', 'branch', 'site'],
    examplePhrases: ['downtown location', 'all stores', 'main branch'],
  },
  {
    slug: 'item',
    displayName: 'Item',
    description: 'Product or menu item name',
    domain: 'core',
    category: 'product',
    sqlExpression: 'catalog_item_name',
    sqlTable: 'rm_item_sales',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['product', 'menu item', 'sku', 'item name'],
    examplePhrases: ['burger', 'top products', 'best sellers', 'top selling items'],
  },
  {
    slug: 'week',
    displayName: 'Week',
    description: 'ISO week number',
    domain: 'core',
    category: 'time',
    sqlExpression: "DATE_TRUNC('week', business_date)",
    sqlTable: 'rm_daily_sales',
    sqlDataType: 'date',
    hierarchyParent: 'date',
    hierarchyLevel: 1,
    isTimeDimension: true,
    timeGranularities: ['week'],
    aliases: ['weekly'],
    examplePhrases: ['this week', 'last week', 'week of'],
  },
  {
    slug: 'month',
    displayName: 'Month',
    description: 'Calendar month',
    domain: 'core',
    category: 'time',
    sqlExpression: "DATE_TRUNC('month', business_date)",
    sqlTable: 'rm_daily_sales',
    sqlDataType: 'date',
    hierarchyParent: 'week',
    hierarchyLevel: 2,
    isTimeDimension: true,
    timeGranularities: ['month'],
    aliases: ['monthly'],
    examplePhrases: ['this month', 'last month', 'January'],
  },
  // ── Inventory dimensions ──────────────────────────────────────
  {
    slug: 'inventory_item',
    displayName: 'Inventory Item',
    description: 'Product name in inventory',
    domain: 'inventory',
    category: 'product',
    sqlExpression: 'item_name',
    sqlTable: 'rm_inventory_on_hand',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['stock item', 'product', 'inventory product'],
    examplePhrases: ['which items', 'stock levels by item', 'low stock items'],
  },
  {
    slug: 'inventory_location',
    displayName: 'Inventory Location',
    description: 'Location for inventory snapshot',
    domain: 'inventory',
    category: 'geography',
    sqlExpression: 'location_id',
    sqlTable: 'rm_inventory_on_hand',
    sqlDataType: 'text',
    isTimeDimension: false,
    lookupTable: 'locations',
    lookupKeyColumn: 'id',
    lookupLabelColumn: 'name',
    aliases: ['warehouse', 'store', 'location'],
    examplePhrases: ['by location', 'at downtown', 'each store'],
  },
  // ── Customer dimensions ───────────────────────────────────────
  {
    slug: 'customer',
    displayName: 'Customer',
    description: 'Customer name',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'customer_name',
    sqlTable: 'rm_customer_activity',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['guest', 'member', 'patron', 'client'],
    examplePhrases: ['top customers', 'best customers', 'most frequent visitors'],
  },
];

// ── Core Metrics ──────────────────────────────────────────────────

export const CORE_METRICS: Omit<MetricDef, 'isActive' | 'isExperimental'>[] = [
  // ── rm_daily_sales metrics ────────────────────────────────────
  {
    slug: 'net_sales',
    displayName: 'Net Sales',
    description: 'Total sales revenue after voids, net of refunds',
    domain: 'core',
    category: 'revenue',
    sqlExpression: 'SUM(net_sales)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['revenue', 'sales', 'total sales', 'gross revenue', 'income'],
    examplePhrases: [
      'how much did we sell',
      'what were our sales',
      'show me revenue',
      'total sales yesterday',
    ],
    relatedMetrics: ['gross_sales', 'order_count', 'avg_order_value'],
  },
  {
    slug: 'gross_sales',
    displayName: 'Gross Sales',
    description: 'Total sales before voids and returns',
    domain: 'core',
    category: 'revenue',
    sqlExpression: 'SUM(gross_sales)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['gross revenue', 'pre-void sales'],
    examplePhrases: ['gross sales', 'before voids'],
    relatedMetrics: ['net_sales', 'void_total'],
  },
  {
    slug: 'order_count',
    displayName: 'Order Count',
    description: 'Number of completed orders',
    domain: 'core',
    category: 'volume',
    sqlExpression: 'SUM(order_count)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'orders',
    higherIsBetter: true,
    aliases: ['transactions', 'orders', 'ticket count', 'covers'],
    examplePhrases: [
      'how many orders',
      'number of transactions',
      'ticket count',
      'how many customers served',
    ],
    relatedMetrics: ['net_sales', 'avg_order_value'],
  },
  {
    slug: 'avg_order_value',
    displayName: 'Average Order Value',
    description: 'Average revenue per completed order',
    domain: 'core',
    category: 'efficiency',
    sqlExpression: 'SUM(net_sales) / NULLIF(SUM(order_count), 0)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'custom',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['aov', 'check average', 'average ticket', 'average check'],
    examplePhrases: [
      'what is our average ticket',
      'average order size',
      'check average',
      'average spend per customer',
    ],
    relatedMetrics: ['net_sales', 'order_count'],
    incompatibleWith: ['items_sold'],
  },
  {
    slug: 'void_count',
    displayName: 'Void Count',
    description: 'Number of voided orders',
    domain: 'core',
    category: 'operations',
    sqlExpression: 'SUM(void_count)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    higherIsBetter: false,
    aliases: ['voids', 'cancellations', 'cancelled orders'],
    examplePhrases: ['how many voids', 'cancelled orders', 'void rate'],
    relatedMetrics: ['void_total', 'order_count'],
  },
  {
    slug: 'void_total',
    displayName: 'Void Amount',
    description: 'Total dollar value of voided orders',
    domain: 'core',
    category: 'operations',
    sqlExpression: 'SUM(void_total)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: false,
    aliases: ['voids amount', 'voided sales'],
    examplePhrases: ['void total', 'how much was voided'],
    relatedMetrics: ['void_count', 'net_sales'],
  },
  {
    slug: 'discount_total',
    displayName: 'Discount Total',
    description: 'Total discount amount applied to orders',
    domain: 'core',
    category: 'revenue',
    sqlExpression: 'SUM(discount_total)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: false,
    aliases: ['discounts', 'promo amount', 'discount amount'],
    examplePhrases: ['how much did we discount', 'discount total', 'promo spend'],
    relatedMetrics: ['net_sales', 'gross_sales'],
  },
  {
    slug: 'tax_total',
    displayName: 'Tax Collected',
    description: 'Total tax amount collected on orders',
    domain: 'core',
    category: 'revenue',
    sqlExpression: 'SUM(tax_total)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: null,
    aliases: ['taxes', 'tax collected', 'sales tax'],
    examplePhrases: ['how much tax collected', 'tax total', 'taxes today'],
    relatedMetrics: ['net_sales', 'gross_sales'],
  },
  {
    slug: 'tender_cash',
    displayName: 'Cash Payments',
    description: 'Total cash tender amount received',
    domain: 'core',
    category: 'payments',
    sqlExpression: 'SUM(tender_cash)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: null,
    aliases: ['cash', 'cash received', 'cash payments'],
    examplePhrases: ['how much cash', 'cash payments today', 'cash vs card'],
    relatedMetrics: ['tender_card', 'net_sales'],
  },
  {
    slug: 'tender_card',
    displayName: 'Card Payments',
    description: 'Total card/credit tender amount received',
    domain: 'core',
    category: 'payments',
    sqlExpression: 'SUM(tender_card)',
    sqlTable: 'rm_daily_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: null,
    aliases: ['card', 'credit card', 'card payments'],
    examplePhrases: ['how much on card', 'card payments today', 'credit card total'],
    relatedMetrics: ['tender_cash', 'net_sales'],
  },
  // ── rm_item_sales metrics (FIXED: use actual column names) ────
  {
    slug: 'items_sold',
    displayName: 'Items Sold',
    description: 'Total quantity of items sold',
    domain: 'core',
    category: 'volume',
    sqlExpression: 'SUM(quantity_sold)',
    sqlTable: 'rm_item_sales',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'units',
    higherIsBetter: true,
    aliases: ['units sold', 'quantity', 'items', 'qty', 'top selling'],
    examplePhrases: ['how many items sold', 'top selling items', 'quantity sold', 'best sellers'],
    relatedMetrics: ['net_sales', 'item_revenue'],
    incompatibleWith: ['avg_order_value'],
  },
  {
    slug: 'item_revenue',
    displayName: 'Item Revenue',
    description: 'Gross revenue attributed to specific items',
    domain: 'core',
    category: 'revenue',
    sqlExpression: 'SUM(gross_revenue)',
    sqlTable: 'rm_item_sales',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['item sales', 'product revenue', 'item gross'],
    examplePhrases: ['revenue by item', 'top items by revenue', 'highest earning items'],
    relatedMetrics: ['items_sold'],
  },
  {
    slug: 'items_voided',
    displayName: 'Items Voided',
    description: 'Quantity of items voided',
    domain: 'core',
    category: 'operations',
    sqlExpression: 'SUM(quantity_voided)',
    sqlTable: 'rm_item_sales',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'units',
    higherIsBetter: false,
    aliases: ['voided items', 'quantity voided'],
    examplePhrases: ['voided items', 'which items got voided'],
    relatedMetrics: ['items_sold', 'void_count'],
  },
  // ── rm_inventory_on_hand metrics (snapshot — no date dimension) ──
  {
    slug: 'on_hand_qty',
    displayName: 'On Hand Quantity',
    description: 'Current total units in stock across inventory (snapshot — not time-series)',
    domain: 'inventory',
    category: 'inventory',
    sqlExpression: 'SUM(on_hand)',
    sqlTable: 'rm_inventory_on_hand',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'units',
    higherIsBetter: true,
    aliases: ['stock', 'inventory', 'on hand', 'stock level', 'quantity on hand'],
    examplePhrases: ['how much stock do we have', 'inventory levels', 'what is on hand', 'stock quantity'],
    relatedMetrics: ['low_stock_count'],
  },
  {
    slug: 'low_stock_count',
    displayName: 'Low Stock Items',
    description: 'Number of items currently below their reorder threshold (snapshot)',
    domain: 'inventory',
    category: 'inventory',
    sqlExpression: 'COUNT(*) FILTER (WHERE is_below_threshold = true)',
    sqlTable: 'rm_inventory_on_hand',
    sqlAggregation: 'custom',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'items',
    higherIsBetter: false,
    aliases: ['low stock', 'reorder needed', 'below threshold', 'out of stock'],
    examplePhrases: ['how many items are low stock', 'what needs reordering', 'low stock alert'],
    relatedMetrics: ['on_hand_qty', 'inventory_item_count'],
  },
  {
    slug: 'inventory_item_count',
    displayName: 'Inventory Item Count',
    description: 'Number of distinct inventory items tracked (snapshot)',
    domain: 'inventory',
    category: 'inventory',
    sqlExpression: 'COUNT(*)',
    sqlTable: 'rm_inventory_on_hand',
    sqlAggregation: 'count',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'items',
    higherIsBetter: null,
    aliases: ['product count', 'item count', 'SKU count'],
    examplePhrases: ['how many items in inventory', 'total products tracked'],
    relatedMetrics: ['on_hand_qty', 'low_stock_count'],
  },
  // ── rm_customer_activity metrics (running total — no date dimension) ──
  {
    slug: 'customer_count',
    displayName: 'Customer Count',
    description: 'Total number of unique customers',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'COUNT(*)',
    sqlTable: 'rm_customer_activity',
    sqlAggregation: 'count',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'customers',
    higherIsBetter: true,
    aliases: ['total customers', 'guest count', 'client count'],
    examplePhrases: ['how many customers', 'total customers', 'customer base size'],
    relatedMetrics: ['total_customer_visits', 'total_customer_spend'],
  },
  {
    slug: 'total_customer_visits',
    displayName: 'Total Customer Visits',
    description: 'Sum of all customer visits across all customers',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'SUM(total_visits)',
    sqlTable: 'rm_customer_activity',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'visits',
    higherIsBetter: true,
    aliases: ['visits', 'total visits', 'foot traffic'],
    examplePhrases: ['total visits', 'customer visits', 'who visits most'],
    relatedMetrics: ['customer_count', 'total_customer_spend'],
  },
  {
    slug: 'total_customer_spend',
    displayName: 'Total Customer Spend',
    description: 'Sum of all customer lifetime spend',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'SUM(total_spend)',
    sqlTable: 'rm_customer_activity',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['lifetime spend', 'customer revenue', 'total spend'],
    examplePhrases: ['total customer spend', 'who spends the most', 'top spenders', 'best customers'],
    relatedMetrics: ['customer_count', 'total_customer_visits', 'avg_customer_spend'],
  },
  {
    slug: 'avg_customer_spend',
    displayName: 'Avg Customer Spend',
    description: 'Average lifetime spend per customer',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'SUM(total_spend) / NULLIF(COUNT(*), 0)',
    sqlTable: 'rm_customer_activity',
    sqlAggregation: 'custom',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['average spend', 'spend per customer', 'average CLV'],
    examplePhrases: ['average spend per customer', 'average customer value', 'CLV'],
    relatedMetrics: ['total_customer_spend', 'customer_count'],
  },
  {
    slug: 'avg_customer_visits',
    displayName: 'Avg Customer Visits',
    description: 'Average number of visits per customer',
    domain: 'customer',
    category: 'customer',
    sqlExpression: 'SUM(total_visits) / NULLIF(COUNT(*), 0)',
    sqlTable: 'rm_customer_activity',
    sqlAggregation: 'custom',
    dataType: 'number',
    formatPattern: '0.0',
    unit: 'visits',
    higherIsBetter: true,
    aliases: ['average visits', 'visits per customer', 'visit frequency'],
    examplePhrases: ['how often do customers visit', 'average visits per customer', 'visit frequency'],
    relatedMetrics: ['total_customer_visits', 'customer_count'],
  },
];

// ── Golf Dimensions ───────────────────────────────────────────────

export const GOLF_DIMENSIONS: Omit<DimensionDef, 'isActive'>[] = [
  {
    slug: 'golf_course',
    displayName: 'Course',
    description: 'Golf course',
    domain: 'golf',
    category: 'golf',
    sqlExpression: 'course_id',
    sqlTable: 'rm_golf_daily_revenue',
    sqlDataType: 'text',
    isTimeDimension: false,
    lookupTable: 'courses',
    lookupKeyColumn: 'id',
    lookupLabelColumn: 'name',
    aliases: ['course', 'track'],
    examplePhrases: ['course 1', 'the back nine', 'championship course'],
  },
  {
    slug: 'booking_channel',
    displayName: 'Booking Channel',
    description: 'How the round was booked',
    domain: 'golf',
    category: 'golf',
    sqlExpression: 'channel',
    sqlTable: 'rm_golf_channel_daily',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['channel', 'source', 'booking source'],
    exampleValues: ['walk_in', 'online', 'phone', 'third_party', 'member'],
    examplePhrases: ['online bookings', 'walk-ins', 'phone reservations'],
  },
  {
    slug: 'daypart',
    displayName: 'Daypart',
    description: 'Time segment of day (morning, afternoon, twilight)',
    domain: 'golf',
    category: 'golf',
    sqlExpression: 'daypart',
    sqlTable: 'rm_golf_daypart_revenue',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['time of day', 'shift', 'session'],
    exampleValues: ['morning', 'afternoon', 'twilight'],
    examplePhrases: ['morning rounds', 'twilight rates', 'afternoon tee times'],
  },
  {
    slug: 'player_type',
    displayName: 'Player Type',
    description: 'Member, guest, or resort guest',
    domain: 'golf',
    category: 'golf',
    sqlExpression: 'player_type',
    sqlTable: 'rm_golf_daily_revenue',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['member type', 'customer type', 'guest type'],
    exampleValues: ['member', 'guest', 'resort_guest', 'comp'],
    examplePhrases: ['member rounds', 'guest rounds', 'resort guests'],
  },
  {
    slug: 'holes',
    displayName: 'Holes',
    description: 'Number of holes played (9 or 18)',
    domain: 'golf',
    category: 'golf',
    sqlExpression: 'holes_played',
    sqlTable: 'rm_golf_daily_revenue',
    sqlDataType: 'integer',
    isTimeDimension: false,
    aliases: ['9 holes', '18 holes', 'front nine', 'back nine'],
    exampleValues: ['9', '18'],
    examplePhrases: ['9-hole rounds', '18-hole games', 'front nine only'],
  },
  {
    slug: 'day_of_week',
    displayName: 'Day of Week',
    description: 'Day of the week (Monday–Sunday) for pattern analysis',
    domain: 'golf',
    category: 'time',
    sqlExpression: "TO_CHAR(business_date, 'Day')",
    sqlTable: 'rm_golf_daily_revenue',
    sqlDataType: 'text',
    isTimeDimension: false,
    aliases: ['weekday', 'day', 'dow'],
    exampleValues: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    examplePhrases: ['weekday vs weekend', 'busiest day', 'Saturday performance'],
  },
];

// ── Golf Metrics ──────────────────────────────────────────────────

export const GOLF_METRICS: Omit<MetricDef, 'isActive' | 'isExperimental'>[] = [
  {
    slug: 'rounds_played',
    displayName: 'Rounds Played',
    description: 'Number of rounds of golf completed',
    domain: 'golf',
    category: 'volume',
    sqlExpression: 'SUM(rounds_played)',
    sqlTable: 'rm_golf_daily_revenue',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'rounds',
    higherIsBetter: true,
    aliases: ['rounds', 'games', 'tee times played', 'round count'],
    examplePhrases: [
      'how many rounds',
      'rounds played today',
      'tee time count',
      'how busy were we',
    ],
    relatedMetrics: ['green_fee_revenue', 'utilization_rate'],
  },
  {
    slug: 'green_fee_revenue',
    displayName: 'Green Fee Revenue',
    description: 'Revenue from green fees (excludes cart, F&B)',
    domain: 'golf',
    category: 'revenue',
    sqlExpression: 'SUM(green_fee_revenue)',
    sqlTable: 'rm_golf_daily_revenue',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['green fees', 'greens revenue', 'tee time revenue'],
    examplePhrases: ['green fee revenue', 'how much from green fees'],
    relatedMetrics: ['rounds_played', 'revenue_per_round'],
  },
  {
    slug: 'revenue_per_round',
    displayName: 'Revenue Per Round',
    description: 'Average green fee revenue per round played',
    domain: 'golf',
    category: 'efficiency',
    sqlExpression: 'SUM(green_fee_revenue) / NULLIF(SUM(rounds_played), 0)',
    sqlTable: 'rm_golf_daily_revenue',
    sqlAggregation: 'custom',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['yield per round', 'average green fee', 'rev per round'],
    examplePhrases: ['average revenue per round', 'yield', 'how much per round'],
    relatedMetrics: ['green_fee_revenue', 'rounds_played'],
  },
  {
    slug: 'utilization_rate',
    displayName: 'Utilization Rate',
    description: 'Percentage of available tee times that were played',
    domain: 'golf',
    category: 'efficiency',
    sqlExpression: 'SUM(rounds_played)::NUMERIC / NULLIF(SUM(available_slots), 0) * 100',
    sqlTable: 'rm_golf_utilization',
    sqlAggregation: 'custom',
    dataType: 'percent',
    formatPattern: '0.0%',
    higherIsBetter: true,
    aliases: ['occupancy', 'fill rate', 'tee sheet utilization'],
    examplePhrases: [
      'utilization rate',
      'how full were we',
      'tee sheet occupancy',
      'fill rate',
    ],
    relatedMetrics: ['rounds_played'],
    requiresDimensions: ['date'],
  },
  {
    slug: 'avg_pace_of_play',
    displayName: 'Avg Pace of Play',
    description: 'Average round duration in minutes',
    domain: 'golf',
    category: 'operations',
    sqlExpression: 'AVG(avg_pace_minutes)',
    sqlTable: 'rm_golf_pace_daily',
    sqlAggregation: 'avg',
    dataType: 'duration',
    formatPattern: '0,0',
    unit: 'minutes',
    higherIsBetter: false,
    aliases: ['pace of play', 'round time', 'average pace', 'round duration'],
    examplePhrases: [
      'average pace of play',
      'how long do rounds take',
      'round time',
      'pace tracking',
    ],
    relatedMetrics: ['rounds_played'],
  },
  {
    slug: 'total_golf_revenue',
    displayName: 'Total Golf Revenue',
    description: 'All golf revenue: green fees + cart + instruction + other',
    domain: 'golf',
    category: 'revenue',
    sqlExpression: 'SUM(total_revenue)',
    sqlTable: 'rm_golf_daily_revenue',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['golf revenue', 'total revenue', 'golf income'],
    examplePhrases: ['total golf revenue', 'all golf income', 'how much golf revenue'],
    relatedMetrics: ['green_fee_revenue', 'rounds_played'],
  },
  {
    slug: 'cart_revenue',
    displayName: 'Cart Revenue',
    description: 'Revenue from golf cart rentals',
    domain: 'golf',
    category: 'revenue',
    sqlExpression: 'SUM(cart_revenue)',
    sqlTable: 'rm_golf_daily_revenue',
    sqlAggregation: 'sum',
    dataType: 'currency',
    formatPattern: '$0,0.00',
    unit: 'USD',
    higherIsBetter: true,
    aliases: ['cart rental', 'cart income', 'golf cart revenue'],
    examplePhrases: ['cart revenue', 'how much from cart rentals', 'cart income'],
    relatedMetrics: ['total_golf_revenue', 'rounds_played'],
  },
  {
    slug: 'available_tee_times',
    displayName: 'Available Tee Times',
    description: 'Total number of available tee time slots',
    domain: 'golf',
    category: 'operations',
    sqlExpression: 'SUM(available_slots)',
    sqlTable: 'rm_golf_utilization',
    sqlAggregation: 'sum',
    dataType: 'integer',
    formatPattern: '0,0',
    unit: 'slots',
    higherIsBetter: null,
    aliases: ['capacity', 'total slots', 'tee time capacity'],
    examplePhrases: ['how many tee times available', 'total capacity', 'open slots'],
    relatedMetrics: ['rounds_played', 'utilization_rate'],
  },
];

// ── Core Metric–Dimension relations ───────────────────────────────

export const CORE_METRIC_DIMENSIONS: MetricDimensionRelation[] = [
  // net_sales
  { metricSlug: 'net_sales', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'net_sales', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'net_sales', dimensionSlug: 'week', isRequired: false, isDefault: false, sortOrder: 2 },
  { metricSlug: 'net_sales', dimensionSlug: 'month', isRequired: false, isDefault: false, sortOrder: 3 },
  // gross_sales
  { metricSlug: 'gross_sales', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'gross_sales', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // order_count
  { metricSlug: 'order_count', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'order_count', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // avg_order_value
  { metricSlug: 'avg_order_value', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'avg_order_value', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // void_count & void_total
  { metricSlug: 'void_count', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'void_count', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'void_total', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'void_total', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // discount_total
  { metricSlug: 'discount_total', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'discount_total', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // tax_total
  { metricSlug: 'tax_total', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'tax_total', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // tender_cash & tender_card
  { metricSlug: 'tender_cash', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'tender_cash', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'tender_card', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'tender_card', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 1 },
  // items_sold (uses rm_item_sales)
  { metricSlug: 'items_sold', dimensionSlug: 'date', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'items_sold', dimensionSlug: 'item', isRequired: false, isDefault: true, sortOrder: 1 },
  { metricSlug: 'items_sold', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 2 },
  // item_revenue (uses rm_item_sales)
  { metricSlug: 'item_revenue', dimensionSlug: 'date', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'item_revenue', dimensionSlug: 'item', isRequired: false, isDefault: true, sortOrder: 1 },
  { metricSlug: 'item_revenue', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 2 },
  // items_voided (uses rm_item_sales)
  { metricSlug: 'items_voided', dimensionSlug: 'date', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'items_voided', dimensionSlug: 'item', isRequired: false, isDefault: true, sortOrder: 1 },
  { metricSlug: 'items_voided', dimensionSlug: 'location', isRequired: false, isDefault: false, sortOrder: 2 },
  // inventory metrics (snapshot — no date dimension)
  { metricSlug: 'on_hand_qty', dimensionSlug: 'inventory_item', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'on_hand_qty', dimensionSlug: 'inventory_location', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'low_stock_count', dimensionSlug: 'inventory_location', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'inventory_item_count', dimensionSlug: 'inventory_location', isRequired: false, isDefault: false, sortOrder: 0 },
  // customer metrics (running total — no date dimension)
  { metricSlug: 'customer_count', dimensionSlug: 'customer', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'total_customer_visits', dimensionSlug: 'customer', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'total_customer_spend', dimensionSlug: 'customer', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'avg_customer_spend', dimensionSlug: 'customer', isRequired: false, isDefault: false, sortOrder: 0 },
  { metricSlug: 'avg_customer_visits', dimensionSlug: 'customer', isRequired: false, isDefault: false, sortOrder: 0 },
];

// ── Golf Metric–Dimension relations ───────────────────────────────

export const GOLF_METRIC_DIMENSIONS: MetricDimensionRelation[] = [
  { metricSlug: 'rounds_played', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'rounds_played', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'rounds_played', dimensionSlug: 'booking_channel', isRequired: false, isDefault: false, sortOrder: 2 },
  { metricSlug: 'rounds_played', dimensionSlug: 'daypart', isRequired: false, isDefault: false, sortOrder: 3 },
  { metricSlug: 'rounds_played', dimensionSlug: 'player_type', isRequired: false, isDefault: false, sortOrder: 4 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'booking_channel', isRequired: false, isDefault: false, sortOrder: 2 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'player_type', isRequired: false, isDefault: false, sortOrder: 3 },
  { metricSlug: 'revenue_per_round', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'revenue_per_round', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'revenue_per_round', dimensionSlug: 'booking_channel', isRequired: false, isDefault: false, sortOrder: 2 },
  { metricSlug: 'utilization_rate', dimensionSlug: 'date', isRequired: true, isDefault: true, sortOrder: 0 },
  { metricSlug: 'utilization_rate', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'avg_pace_of_play', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'avg_pace_of_play', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'total_golf_revenue', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'total_golf_revenue', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  // cart_revenue
  { metricSlug: 'cart_revenue', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'cart_revenue', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'cart_revenue', dimensionSlug: 'player_type', isRequired: false, isDefault: false, sortOrder: 2 },
  // available_tee_times
  { metricSlug: 'available_tee_times', dimensionSlug: 'date', isRequired: false, isDefault: true, sortOrder: 0 },
  { metricSlug: 'available_tee_times', dimensionSlug: 'golf_course', isRequired: false, isDefault: false, sortOrder: 1 },
  { metricSlug: 'available_tee_times', dimensionSlug: 'daypart', isRequired: false, isDefault: false, sortOrder: 2 },
  // day_of_week dimension relations
  { metricSlug: 'rounds_played', dimensionSlug: 'day_of_week', isRequired: false, isDefault: false, sortOrder: 5 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'day_of_week', isRequired: false, isDefault: false, sortOrder: 4 },
  { metricSlug: 'total_golf_revenue', dimensionSlug: 'day_of_week', isRequired: false, isDefault: false, sortOrder: 2 },
  // holes dimension relations
  { metricSlug: 'rounds_played', dimensionSlug: 'holes', isRequired: false, isDefault: false, sortOrder: 6 },
  { metricSlug: 'green_fee_revenue', dimensionSlug: 'holes', isRequired: false, isDefault: false, sortOrder: 5 },
];

// ── System Lenses ─────────────────────────────────────────────────

export const SYSTEM_LENSES: Omit<LensDef, 'isActive'>[] = [
  {
    slug: 'core_sales',
    displayName: 'Sales & Revenue',
    description: 'Daily sales, order counts, revenue, discounts, taxes, and payment methods',
    domain: 'core',
    isSystem: true,
    allowedMetrics: ['net_sales', 'gross_sales', 'order_count', 'avg_order_value', 'void_count', 'void_total', 'discount_total', 'tax_total', 'tender_cash', 'tender_card'],
    allowedDimensions: ['date', 'location', 'week', 'month'],
    defaultMetrics: ['net_sales', 'order_count'],
    defaultDimensions: ['date'],
    exampleQuestions: [
      'How were sales yesterday?',
      'What is our revenue this week?',
      'How does today compare to last Tuesday?',
      'Which location had the most sales?',
      'How much did we discount?',
      'Cash vs card payments?',
    ],
    systemPromptFragment:
      'You are analyzing sales and revenue data. Key metrics: net_sales, order_count, avg_order_value, discount_total, tax_total, tender_cash, tender_card. Always include a date dimension unless asked otherwise.',
  },
  {
    slug: 'core_items',
    displayName: 'Item Performance',
    description: 'Item-level sales, quantities, and revenue — find top sellers and underperformers',
    domain: 'core',
    isSystem: true,
    allowedMetrics: ['items_sold', 'item_revenue', 'items_voided'],
    allowedDimensions: ['date', 'item', 'location', 'week', 'month'],
    defaultMetrics: ['items_sold', 'item_revenue'],
    defaultDimensions: ['item'],
    exampleQuestions: [
      'What are the top selling items?',
      'Which items bring in the most revenue?',
      'What are our best sellers this week?',
      'Show me items sold today',
    ],
    systemPromptFragment:
      'You are analyzing item-level sales. Use items_sold for quantity and item_revenue for dollar amounts. Group by the item dimension to see per-product breakdown. Default to sorting by items_sold or item_revenue descending with a limit of 20 for "top" queries.',
  },
  {
    slug: 'core_inventory',
    displayName: 'Inventory Status',
    description: 'Current stock levels, low-stock alerts, and inventory overview',
    domain: 'inventory',
    isSystem: true,
    allowedMetrics: ['on_hand_qty', 'low_stock_count', 'inventory_item_count'],
    allowedDimensions: ['inventory_item', 'inventory_location'],
    defaultMetrics: ['on_hand_qty'],
    defaultDimensions: ['inventory_item'],
    exampleQuestions: [
      'What is our inventory status?',
      'How many items are low stock?',
      'Stock levels by location',
      'What needs reordering?',
    ],
    systemPromptFragment:
      'You are analyzing current inventory status. This is SNAPSHOT data (not time-series) — do NOT include date dimensions or date ranges. Key metrics: on_hand_qty (stock level), low_stock_count (items below reorder point), inventory_item_count (total products tracked).',
  },
  {
    slug: 'core_customers',
    displayName: 'Customer Insights',
    description: 'Customer visit frequency, spend patterns, and top customers',
    domain: 'customer',
    isSystem: true,
    allowedMetrics: ['customer_count', 'total_customer_visits', 'total_customer_spend', 'avg_customer_spend', 'avg_customer_visits'],
    allowedDimensions: ['customer'],
    defaultMetrics: ['total_customer_spend', 'total_customer_visits'],
    defaultDimensions: ['customer'],
    exampleQuestions: [
      'Who are our best customers?',
      'How many customers do we have?',
      'Top spenders',
      'Average customer spend',
      'Most frequent visitors',
    ],
    systemPromptFragment:
      'You are analyzing customer engagement data. This is RUNNING TOTAL data (not time-series) — do NOT include date dimensions or date ranges. Key metrics: total_customer_spend (lifetime $), total_customer_visits (lifetime visits), customer_count, avg_customer_spend, avg_customer_visits. Group by customer dimension for "top" queries.',
  },
  {
    slug: 'golf_operations',
    displayName: 'Golf Operations',
    description: 'Rounds played, utilization, pace of play',
    domain: 'golf',
    isSystem: true,
    allowedMetrics: ['rounds_played', 'utilization_rate', 'avg_pace_of_play'],
    allowedDimensions: ['date', 'golf_course', 'booking_channel', 'daypart', 'player_type'],
    defaultMetrics: ['rounds_played', 'utilization_rate'],
    defaultDimensions: ['date'],
    exampleQuestions: [
      'How many rounds were played today?',
      'What was our utilization rate this week?',
      'How fast are rounds playing?',
      'Utilization by channel',
    ],
    systemPromptFragment:
      'You are analyzing golf operations. Key metrics: rounds_played (volume), utilization_rate (efficiency), avg_pace_of_play (operations). Always include date dimension for utilization_rate — it is required.',
  },
  {
    slug: 'golf_revenue',
    displayName: 'Golf Revenue',
    description: 'Green fee revenue, total golf revenue, cart, and yield metrics',
    domain: 'golf',
    isSystem: true,
    allowedMetrics: ['green_fee_revenue', 'total_golf_revenue', 'revenue_per_round', 'rounds_played', 'cart_revenue'],
    allowedDimensions: ['date', 'golf_course', 'booking_channel', 'daypart', 'player_type', 'day_of_week'],
    defaultMetrics: ['total_golf_revenue', 'rounds_played'],
    defaultDimensions: ['date'],
    exampleQuestions: [
      'What was our golf revenue today?',
      'Revenue per round by channel',
      'How much did we earn from green fees?',
      'Golf revenue trend this month',
      'Cart revenue by player type',
    ],
    systemPromptFragment:
      'You are analyzing golf revenue. Use green_fee_revenue for pure green fee analysis, total_golf_revenue for all-in revenue (includes cart), revenue_per_round for yield analysis, and cart_revenue for cart rental income.',
  },
];
