/**
 * Universal Chart of Accounts Seed Data
 *
 * Default COA for ALL Oppsera tenant business types.
 * Seeded on tenant creation — every field is soft-coded and editable by the tenant.
 * Tenants can rename, re-number, deactivate, or add accounts after seeding.
 *
 * Numbering scheme (5-digit):
 *   10000–14999  Current Assets
 *   15000–15999  Fixed Assets
 *   16000–16999  Intangible Assets
 *   20000–23999  Current Liabilities
 *   24000–25999  Long-Term Liabilities
 *   30000–33999  Equity
 *   40000–43999  Revenue
 *   49000–49999  Contra Revenue
 *   50000–51999  Cost of Goods Sold
 *   60000–69999  Operating Expenses
 *   70000–79999  Reserved (future expense categories)
 *   80000–82999  Other Income / Expense
 *   90000–99999  Statistical / System
 *
 * Integration note — existing Oppsera schema mapping:
 *   Seed type    →  gl_accounts.account_type
 *   ASSET        →  'asset'
 *   LIABILITY    →  'liability'
 *   EQUITY       →  'equity'
 *   REVENUE      →  'revenue'
 *   COGS         →  'expense'   (classification: "Cost of Goods Sold")
 *   EXPENSE      →  'expense'
 *   OTHER_INCOME →  'revenue'   (classification: "Other Income")
 *   OTHER_EXPENSE→  'expense'   (classification: "Other Expense")
 */

import type { AccountRole } from './account-role-map';

// ── Type definitions ────────────────────────────────────────────────

export type AccountType =
  | 'ASSET'
  | 'LIABILITY'
  | 'EQUITY'
  | 'REVENUE'
  | 'COGS'
  | 'EXPENSE'
  | 'OTHER_INCOME'
  | 'OTHER_EXPENSE';

export type NormalBalance = 'DEBIT' | 'CREDIT';

export interface SeedAccount {
  accountNumber: string;
  name: string;
  type: AccountType;
  subType: string;
  normalBalance: NormalBalance;
  isControl: boolean;
  parentAccountNumber: string | null;
  isActive: boolean;
  description: string;
  accountRole: AccountRole | null;
}

// ── Mapping to existing Oppsera 5-type schema ───────────────────────
// Use this when inserting into gl_accounts.account_type
export const ACCOUNT_TYPE_TO_GL_TYPE: Record<AccountType, string> = {
  ASSET: 'asset',
  LIABILITY: 'liability',
  EQUITY: 'equity',
  REVENUE: 'revenue',
  COGS: 'expense',
  EXPENSE: 'expense',
  OTHER_INCOME: 'revenue',
  OTHER_EXPENSE: 'expense',
};

export const ACCOUNT_TYPE_TO_CLASSIFICATION: Record<AccountType, string> = {
  ASSET: '', // determined by subType
  LIABILITY: '', // determined by subType
  EQUITY: '', // determined by subType
  REVENUE: 'Operating Revenue',
  COGS: 'Cost of Goods Sold',
  EXPENSE: '', // determined by subType
  OTHER_INCOME: 'Other Income',
  OTHER_EXPENSE: 'Other Expense',
};

// ── Complete seed data ──────────────────────────────────────────────

export const SEED_ACCOUNTS: SeedAccount[] = [
  // ═══════════════════════════════════════════════════════════════════
  // ASSETS (10000–16999)
  // ═══════════════════════════════════════════════════════════════════

  // ── Cash & Bank Accounts ────────────────────────────────────────
  {
    accountNumber: '10000',
    name: 'Cash & Bank Accounts',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all cash and bank sub-accounts',
    accountRole: null,
  },
  {
    accountNumber: '10100',
    name: 'Cash - Operating Account',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Primary operating bank account for daily business transactions',
    accountRole: 'CASH_OPERATING',
  },
  {
    accountNumber: '10200',
    name: 'Petty Cash',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Small on-hand cash fund for minor incidental expenses',
    accountRole: 'CASH_PETTY',
  },
  {
    accountNumber: '10300',
    name: 'Cash - Safe',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Cash held in physical safe pending deposit',
    accountRole: 'CASH_SAFE',
  },
  {
    accountNumber: '10400',
    name: 'Undeposited Funds',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Payments received but not yet deposited to the bank',
    accountRole: 'UNDEPOSITED_FUNDS',
  },
  {
    accountNumber: '10500',
    name: 'Merchant Clearing Account',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Clearing account for credit/debit card transactions pending settlement',
    accountRole: 'MERCHANT_CLEARING',
  },
  {
    accountNumber: '10600',
    name: 'Gift Card Clearing Account',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '10000',
    isActive: true,
    description: 'Clearing account for gift card redemptions pending processing',
    accountRole: 'GIFT_CARD_CLEARING',
  },

  // ── Accounts Receivable ─────────────────────────────────────────
  {
    accountNumber: '11000',
    name: 'Accounts Receivable',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all trade receivables owed by customers',
    accountRole: 'AR_CONTROL',
  },
  {
    accountNumber: '11100',
    name: 'AR - House Accounts',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '11000',
    isActive: true,
    description: 'Receivables from individual house account customers (POS charge-to-account)',
    accountRole: 'AR_HOUSE',
  },
  {
    accountNumber: '11200',
    name: 'AR - Corporate Accounts',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '11000',
    isActive: true,
    description: 'Receivables from corporate billing accounts and group invoices',
    accountRole: 'AR_CORPORATE',
  },

  // ── Inventory ───────────────────────────────────────────────────
  {
    accountNumber: '12000',
    name: 'Inventory',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all inventory asset sub-accounts',
    accountRole: 'INVENTORY_CONTROL',
  },
  {
    accountNumber: '12100',
    name: 'Inventory - Retail Merchandise',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '12000',
    isActive: true,
    description: 'Cost of retail goods held for resale (pro shop, gift shop, general merchandise)',
    accountRole: 'INVENTORY_RETAIL',
  },
  {
    accountNumber: '12200',
    name: 'Inventory - Food',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '12000',
    isActive: true,
    description: 'Cost of food ingredients and prepared items held for sale',
    accountRole: 'INVENTORY_FOOD',
  },
  {
    accountNumber: '12300',
    name: 'Inventory - Beverage',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '12000',
    isActive: true,
    description: 'Cost of alcoholic and non-alcoholic beverages held for sale',
    accountRole: 'INVENTORY_BEVERAGE',
  },
  {
    accountNumber: '12400',
    name: 'Inventory - Supplies',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '12000',
    isActive: true,
    description: 'Consumable operating supplies (cleaning, packaging, disposables)',
    accountRole: 'INVENTORY_SUPPLIES',
  },
  {
    accountNumber: '12500',
    name: 'Inventory - Rental & Equipment',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '12000',
    isActive: true,
    description: 'Rental inventory items (golf carts, boats, equipment for hire)',
    accountRole: 'INVENTORY_RENTAL',
  },

  // ── Prepaid Expenses ────────────────────────────────────────────
  {
    accountNumber: '13000',
    name: 'Prepaid Expenses',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for expenses paid in advance of the benefit period',
    accountRole: null,
  },
  {
    accountNumber: '13100',
    name: 'Prepaid Insurance',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '13000',
    isActive: true,
    description: 'Insurance premiums paid in advance, amortized monthly',
    accountRole: null,
  },
  {
    accountNumber: '13200',
    name: 'Prepaid Rent',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '13000',
    isActive: true,
    description: 'Rent or lease payments made in advance of the occupancy period',
    accountRole: null,
  },
  {
    accountNumber: '13300',
    name: 'Prepaid Licenses & Permits',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '13000',
    isActive: true,
    description: 'License and permit fees paid in advance (liquor, health, business)',
    accountRole: null,
  },

  // ── Other Current Assets ────────────────────────────────────────
  {
    accountNumber: '14000',
    name: 'Other Current Assets',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for miscellaneous short-term assets',
    accountRole: null,
  },
  {
    accountNumber: '14100',
    name: 'Utility Deposits',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '14000',
    isActive: true,
    description: 'Refundable deposits held by utility providers',
    accountRole: null,
  },
  {
    accountNumber: '14200',
    name: 'Vendor Deposits',
    type: 'ASSET',
    subType: 'Current Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '14000',
    isActive: true,
    description: 'Advance deposits paid to vendors or suppliers',
    accountRole: null,
  },

  // ── Fixed Assets ────────────────────────────────────────────────
  {
    accountNumber: '15000',
    name: 'Fixed Assets',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all long-lived tangible property and equipment',
    accountRole: null,
  },
  {
    accountNumber: '15100',
    name: 'Land',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Cost of land owned (not depreciated)',
    accountRole: null,
  },
  {
    accountNumber: '15150',
    name: 'Land Improvements',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Improvements to land (parking lots, landscaping, irrigation, fencing)',
    accountRole: null,
  },
  {
    accountNumber: '15200',
    name: 'Buildings',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Cost of owned buildings and permanent structures',
    accountRole: null,
  },
  {
    accountNumber: '15300',
    name: 'Leasehold Improvements',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Improvements made to leased property (build-outs, fixtures, signage)',
    accountRole: null,
  },
  {
    accountNumber: '15400',
    name: 'Furniture & Fixtures',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Tables, chairs, shelving, display cases, and permanent fixtures',
    accountRole: null,
  },
  {
    accountNumber: '15500',
    name: 'Equipment - General',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'General business equipment (tools, machines, appliances)',
    accountRole: null,
  },
  {
    accountNumber: '15600',
    name: 'POS Hardware & Equipment',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Point-of-sale terminals, card readers, receipt printers, scanners',
    accountRole: null,
  },
  {
    accountNumber: '15700',
    name: 'Kitchen Equipment',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Commercial kitchen equipment (ovens, refrigerators, prep stations)',
    accountRole: null,
  },
  {
    accountNumber: '15800',
    name: 'Golf Course Equipment',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Mowers, carts, irrigation systems, and course maintenance equipment',
    accountRole: null,
  },
  {
    accountNumber: '15850',
    name: 'Vehicles',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Company-owned vehicles (delivery, shuttle, utility)',
    accountRole: null,
  },
  {
    accountNumber: '15900',
    name: 'Marina Equipment',
    type: 'ASSET',
    subType: 'Fixed Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Docks, lifts, fuel systems, and marine maintenance equipment',
    accountRole: null,
  },
  {
    accountNumber: '15999',
    name: 'Accumulated Depreciation',
    type: 'ASSET',
    subType: 'Contra Asset',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '15000',
    isActive: true,
    description: 'Total accumulated depreciation on all fixed assets (contra-asset)',
    accountRole: null,
  },

  // ── Intangible Assets ───────────────────────────────────────────
  {
    accountNumber: '16000',
    name: 'Intangible Assets',
    type: 'ASSET',
    subType: 'Intangible Asset',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for non-physical long-lived assets',
    accountRole: null,
  },
  {
    accountNumber: '16100',
    name: 'Software',
    type: 'ASSET',
    subType: 'Intangible Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '16000',
    isActive: true,
    description: 'Capitalized software purchases and licenses',
    accountRole: null,
  },
  {
    accountNumber: '16200',
    name: 'Development Costs',
    type: 'ASSET',
    subType: 'Intangible Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '16000',
    isActive: true,
    description: 'Capitalized internal or external development costs',
    accountRole: null,
  },
  {
    accountNumber: '16300',
    name: 'Goodwill',
    type: 'ASSET',
    subType: 'Intangible Asset',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '16000',
    isActive: true,
    description: 'Excess purchase price over fair value of net assets in an acquisition',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // LIABILITIES (20000–25999)
  // ═══════════════════════════════════════════════════════════════════

  // ── Accounts Payable ────────────────────────────────────────────
  {
    accountNumber: '20000',
    name: 'Accounts Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all trade payables owed to vendors and suppliers',
    accountRole: 'AP_CONTROL',
  },
  {
    accountNumber: '20100',
    name: 'Credit Cards Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '20000',
    isActive: true,
    description: 'Balances owed on company credit cards',
    accountRole: 'CREDIT_CARDS_PAYABLE',
  },
  {
    accountNumber: '20200',
    name: 'Merchant Fees Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '20000',
    isActive: true,
    description: 'Accrued payment processor fees not yet deducted from settlements',
    accountRole: 'MERCHANT_FEES_PAYABLE',
  },

  // ── Accrued & Tax Liabilities ───────────────────────────────────
  {
    accountNumber: '21000',
    name: 'Accrued Expenses',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for expenses incurred but not yet paid',
    accountRole: null,
  },
  {
    accountNumber: '21100',
    name: 'Payroll Liabilities',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '21000',
    isActive: true,
    description: 'Net wages, withholdings, and deductions owed to employees',
    accountRole: 'PAYROLL_LIABILITIES',
  },
  {
    accountNumber: '21200',
    name: 'Payroll Taxes Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '21000',
    isActive: true,
    description: 'Employer and employee payroll taxes owed to government agencies',
    accountRole: 'PAYROLL_TAXES_PAYABLE',
  },
  {
    accountNumber: '21300',
    name: 'Sales Tax Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '21000',
    isActive: true,
    description: 'Collected sales tax owed to state/local tax authorities',
    accountRole: 'SALES_TAX_PAYABLE',
  },
  {
    accountNumber: '21400',
    name: 'Tips Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '21000',
    isActive: true,
    description: 'Gratuities collected on behalf of employees, pending payout',
    accountRole: 'TIPS_PAYABLE',
  },
  {
    accountNumber: '21500',
    name: 'PTO / Vacation Accrual',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '21000',
    isActive: true,
    description: 'Accrued paid time off liability owed to employees',
    accountRole: null,
  },

  // ── Deferred Revenue ────────────────────────────────────────────
  {
    accountNumber: '22000',
    name: 'Deferred Revenue',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for payments received before services/goods are delivered',
    accountRole: null,
  },
  {
    accountNumber: '22100',
    name: 'Gift Card Liability',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '22000',
    isActive: true,
    description: 'Outstanding gift card balances — revenue recognized upon redemption',
    accountRole: 'GIFT_CARD_LIABILITY',
  },
  {
    accountNumber: '22200',
    name: 'Customer Deposits',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '22000',
    isActive: true,
    description: 'Advance deposits from customers for future goods or services',
    accountRole: 'CUSTOMER_DEPOSITS',
  },
  {
    accountNumber: '22300',
    name: 'Membership Deposits',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '22000',
    isActive: true,
    description: 'Deposits received for membership initiation, refundable or applied to dues',
    accountRole: 'MEMBERSHIP_DEPOSITS',
  },
  {
    accountNumber: '22400',
    name: 'Event Deposits',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '22000',
    isActive: true,
    description: 'Advance deposits for booked events, banquets, and catering contracts',
    accountRole: 'EVENT_DEPOSITS',
  },

  // ── Short-Term Debt ─────────────────────────────────────────────
  {
    accountNumber: '23000',
    name: 'Short-Term Debt',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for borrowings due within one year',
    accountRole: null,
  },
  {
    accountNumber: '23100',
    name: 'Short-Term Notes Payable',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '23000',
    isActive: true,
    description: 'Promissory notes and short-term loans due within 12 months',
    accountRole: null,
  },
  {
    accountNumber: '23200',
    name: 'Line of Credit',
    type: 'LIABILITY',
    subType: 'Current Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '23000',
    isActive: true,
    description: 'Outstanding balance on revolving credit facility',
    accountRole: null,
  },

  // ── Long-Term Liabilities ───────────────────────────────────────
  {
    accountNumber: '24000',
    name: 'Long-Term Liabilities',
    type: 'LIABILITY',
    subType: 'Long-Term Liability',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for obligations due beyond one year',
    accountRole: null,
  },
  {
    accountNumber: '24100',
    name: 'Notes Payable - Long-Term',
    type: 'LIABILITY',
    subType: 'Long-Term Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '24000',
    isActive: true,
    description: 'Long-term promissory notes and term loans',
    accountRole: null,
  },
  {
    accountNumber: '24200',
    name: 'Equipment Loans',
    type: 'LIABILITY',
    subType: 'Long-Term Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '24000',
    isActive: true,
    description: 'Financed equipment purchases with terms beyond one year',
    accountRole: null,
  },
  {
    accountNumber: '24300',
    name: 'Mortgage Payable',
    type: 'LIABILITY',
    subType: 'Long-Term Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '24000',
    isActive: true,
    description: 'Outstanding mortgage on owned real property',
    accountRole: null,
  },
  {
    accountNumber: '24400',
    name: 'Lease Liabilities',
    type: 'LIABILITY',
    subType: 'Long-Term Liability',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '24000',
    isActive: true,
    description: 'Present value of future lease payments under ASC 842 / IFRS 16',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // EQUITY (30000–33999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '30000',
    name: "Owner's Equity",
    type: 'EQUITY',
    subType: 'Owner Equity',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for owner and partner capital contributions',
    accountRole: null,
  },
  {
    accountNumber: '30100',
    name: 'Owner Capital Contributions',
    type: 'EQUITY',
    subType: 'Owner Equity',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '30000',
    isActive: true,
    description: 'Capital invested by the primary owner into the business',
    accountRole: 'OWNER_CAPITAL',
  },
  {
    accountNumber: '30200',
    name: 'Partner Capital',
    type: 'EQUITY',
    subType: 'Owner Equity',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '30000',
    isActive: true,
    description: 'Capital invested by additional partners or co-owners',
    accountRole: null,
  },
  {
    accountNumber: '31000',
    name: 'Retained Earnings',
    type: 'EQUITY',
    subType: 'Retained Earnings',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: null,
    isActive: true,
    description: 'Cumulative net income retained in the business from prior fiscal years',
    accountRole: 'RETAINED_EARNINGS',
  },
  {
    accountNumber: '31100',
    name: 'Current Year Earnings',
    type: 'EQUITY',
    subType: 'Retained Earnings',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: null,
    isActive: true,
    description: 'Net income for the current fiscal year (auto-closed to Retained Earnings at year-end)',
    accountRole: 'CURRENT_YEAR_EARNINGS',
  },
  {
    accountNumber: '32000',
    name: 'Owner Draw / Distributions',
    type: 'EQUITY',
    subType: 'Owner Draw',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: null,
    isActive: true,
    description: 'Withdrawals and distributions taken by owner(s) — reduces equity',
    accountRole: 'OWNER_DRAW',
  },

  // ═══════════════════════════════════════════════════════════════════
  // REVENUE (40000–43999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '40000',
    name: 'Operating Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all primary sales and service revenue',
    accountRole: null,
  },
  {
    accountNumber: '40100',
    name: 'Retail Sales',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from general retail and pro shop product sales',
    accountRole: 'SALES_RETAIL',
  },
  {
    accountNumber: '40200',
    name: 'Food Sales',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from food items sold through restaurant, grill, or snack bar',
    accountRole: 'SALES_FOOD',
  },
  {
    accountNumber: '40300',
    name: 'Beverage Sales - Alcohol',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from beer, wine, spirits, and cocktail sales',
    accountRole: 'SALES_BEVERAGE_ALCOHOL',
  },
  {
    accountNumber: '40400',
    name: 'Beverage Sales - Non-Alcohol',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from soft drinks, coffee, tea, juice, and water',
    accountRole: 'SALES_BEVERAGE_NON_ALCOHOL',
  },
  {
    accountNumber: '40500',
    name: 'Merchandise Sales',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from branded merchandise, apparel, and specialty goods',
    accountRole: 'SALES_MERCHANDISE',
  },
  {
    accountNumber: '40600',
    name: 'Rental Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from equipment, cart, boat, or space rentals',
    accountRole: 'SALES_RENTAL',
  },
  {
    accountNumber: '40700',
    name: 'Service Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from professional services (repairs, alterations, salon, spa)',
    accountRole: 'SALES_SERVICE',
  },
  {
    accountNumber: '40800',
    name: 'Membership Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Recurring membership dues and initiation fees recognized over the period',
    accountRole: 'SALES_MEMBERSHIP',
  },
  {
    accountNumber: '40900',
    name: 'Green Fees / Activity Fees',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from golf green fees, court fees, and facility usage charges',
    accountRole: 'SALES_GREEN_FEES',
  },
  {
    accountNumber: '41000',
    name: 'Lessons / Instruction Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from private/group lessons, clinics, and instructional programs',
    accountRole: 'SALES_LESSONS',
  },
  {
    accountNumber: '41100',
    name: 'Room Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from hotel, lodge, cottage, and short-term rental accommodations',
    accountRole: 'SALES_ROOM',
  },
  {
    accountNumber: '41200',
    name: 'Resort Fees',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Mandatory resort or facility fees charged to lodging guests',
    accountRole: null,
  },
  {
    accountNumber: '41300',
    name: 'Late Checkout Fees',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Fees charged for extended checkout beyond standard time',
    accountRole: null,
  },
  {
    accountNumber: '41400',
    name: 'Event Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from hosted events, private parties, and venue rental',
    accountRole: 'SALES_EVENT',
  },
  {
    accountNumber: '41500',
    name: 'Banquet Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from banquet packages including food, beverage, and service',
    accountRole: null,
  },
  {
    accountNumber: '41600',
    name: 'Catering Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from off-site and on-site catering services',
    accountRole: 'SALES_CATERING',
  },
  {
    accountNumber: '41700',
    name: 'Wedding Revenue',
    type: 'REVENUE',
    subType: 'Operating Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '40000',
    isActive: true,
    description: 'Revenue from wedding ceremonies, receptions, and wedding packages',
    accountRole: null,
  },

  // ── Other Operating Revenue ─────────────────────────────────────
  {
    accountNumber: '42000',
    name: 'Other Operating Revenue',
    type: 'REVENUE',
    subType: 'Other Revenue',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for secondary and ancillary operating revenue streams',
    accountRole: null,
  },
  {
    accountNumber: '42100',
    name: 'Shipping Income',
    type: 'REVENUE',
    subType: 'Other Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '42000',
    isActive: true,
    description: 'Revenue from shipping and delivery charges passed to customers',
    accountRole: null,
  },
  {
    accountNumber: '42200',
    name: 'Service Charges',
    type: 'REVENUE',
    subType: 'Other Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '42000',
    isActive: true,
    description: 'Mandatory service charges and auto-gratuities added to orders',
    accountRole: null,
  },
  {
    accountNumber: '42300',
    name: 'Convenience Fees',
    type: 'REVENUE',
    subType: 'Other Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '42000',
    isActive: true,
    description: 'Fees charged for online ordering, delivery, or premium payment methods',
    accountRole: null,
  },
  {
    accountNumber: '42400',
    name: 'Booking Fees',
    type: 'REVENUE',
    subType: 'Other Revenue',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '42000',
    isActive: true,
    description: 'Non-refundable fees for tee-time, reservation, or event bookings',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // CONTRA REVENUE (49000–49999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '49000',
    name: 'Contra Revenue',
    type: 'REVENUE',
    subType: 'Contra Revenue',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all revenue reductions (discounts, returns, comps)',
    accountRole: null,
  },
  {
    accountNumber: '49100',
    name: 'Discounts Given',
    type: 'REVENUE',
    subType: 'Contra Revenue',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '49000',
    isActive: true,
    description: 'POS and manual discounts applied to orders (percentage or fixed)',
    accountRole: 'DISCOUNTS_GIVEN',
  },
  {
    accountNumber: '49200',
    name: 'Promotions',
    type: 'REVENUE',
    subType: 'Contra Revenue',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '49000',
    isActive: true,
    description: 'Promotional offers, BOGO, and marketing-driven price reductions',
    accountRole: null,
  },
  {
    accountNumber: '49300',
    name: 'Refunds & Returns',
    type: 'REVENUE',
    subType: 'Contra Revenue',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '49000',
    isActive: true,
    description: 'Customer refunds and returned merchandise reversing original revenue',
    accountRole: 'REFUNDS_RETURNS',
  },
  {
    accountNumber: '49400',
    name: 'Comps',
    type: 'REVENUE',
    subType: 'Contra Revenue',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '49000',
    isActive: true,
    description: 'Complimentary items and services given at no charge (manager comps, VIP)',
    accountRole: 'COMPS',
  },

  // ═══════════════════════════════════════════════════════════════════
  // COST OF GOODS SOLD (50000–51999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '50000',
    name: 'Cost of Goods Sold',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all direct costs of products sold',
    accountRole: null,
  },
  {
    accountNumber: '50100',
    name: 'COGS - Retail',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of retail merchandise sold (pro shop, general merchandise)',
    accountRole: 'COGS_RETAIL',
  },
  {
    accountNumber: '50200',
    name: 'COGS - Food',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of food ingredients consumed in the production of food sales',
    accountRole: 'COGS_FOOD',
  },
  {
    accountNumber: '50300',
    name: 'COGS - Beverage Alcohol',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of alcoholic beverages consumed in production of alcohol sales',
    accountRole: 'COGS_BEVERAGE_ALCOHOL',
  },
  {
    accountNumber: '50400',
    name: 'COGS - Beverage Non-Alcohol',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of non-alcoholic beverages (soft drinks, coffee, juices)',
    accountRole: 'COGS_BEVERAGE_NON_ALCOHOL',
  },
  {
    accountNumber: '50500',
    name: 'COGS - Merchandise',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of branded merchandise and apparel sold',
    accountRole: 'COGS_MERCHANDISE',
  },
  {
    accountNumber: '50600',
    name: 'COGS - Supplies',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of consumable supplies used directly in service delivery',
    accountRole: 'COGS_SUPPLIES',
  },
  {
    accountNumber: '50700',
    name: 'Inventory Adjustments',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Inventory count adjustments, corrections, and write-downs',
    accountRole: null,
  },
  {
    accountNumber: '50800',
    name: 'Spoilage',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Cost of perishable inventory that expired or was damaged beyond sale',
    accountRole: null,
  },
  {
    accountNumber: '50900',
    name: 'Shrinkage',
    type: 'COGS',
    subType: 'Cost of Goods Sold',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '50000',
    isActive: true,
    description: 'Inventory losses due to theft, breakage, or unaccounted variance',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // OPERATING EXPENSES (60000–69999)
  // ═══════════════════════════════════════════════════════════════════

  // ── Payroll Expenses ────────────────────────────────────────────
  {
    accountNumber: '60000',
    name: 'Payroll Expenses',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all compensation and benefit costs',
    accountRole: null,
  },
  {
    accountNumber: '60100',
    name: 'Wages - Hourly',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Hourly employee wages (servers, cashiers, line cooks, staff)',
    accountRole: 'WAGES',
  },
  {
    accountNumber: '60200',
    name: 'Salaries',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Salaried employee compensation (managers, administrators)',
    accountRole: 'SALARIES',
  },
  {
    accountNumber: '60300',
    name: 'Overtime',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Overtime premium pay in excess of regular wage rates',
    accountRole: null,
  },
  {
    accountNumber: '60400',
    name: 'Bonuses & Commissions',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Performance bonuses, sales commissions, and incentive payouts',
    accountRole: null,
  },
  {
    accountNumber: '60500',
    name: 'Employer Payroll Taxes',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Employer share of FICA, FUTA, SUTA, and other payroll taxes',
    accountRole: null,
  },
  {
    accountNumber: '60600',
    name: 'Employee Benefits',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Health insurance, dental, vision, life insurance, and other benefits',
    accountRole: null,
  },
  {
    accountNumber: '60700',
    name: '401k / Retirement Contributions',
    type: 'EXPENSE',
    subType: 'Payroll Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '60000',
    isActive: true,
    description: 'Employer matching contributions to 401k, IRA, or pension plans',
    accountRole: null,
  },

  // ── Facilities Expenses ─────────────────────────────────────────
  {
    accountNumber: '61000',
    name: 'Facilities Expenses',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for occupancy, property, and facilities maintenance costs',
    accountRole: null,
  },
  {
    accountNumber: '61100',
    name: 'Rent / Lease Payments',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Monthly rent or lease payments for business premises',
    accountRole: 'RENT_LEASE',
  },
  {
    accountNumber: '61200',
    name: 'Property Taxes',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Real estate and property tax assessments on owned property',
    accountRole: null,
  },
  {
    accountNumber: '61300',
    name: 'Property Insurance',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Property, casualty, and general liability insurance premiums',
    accountRole: null,
  },
  {
    accountNumber: '61400',
    name: 'Utilities',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Electric, gas, water, sewer, and waste disposal services',
    accountRole: null,
  },
  {
    accountNumber: '61500',
    name: 'Repairs & Maintenance',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Building repairs, HVAC maintenance, plumbing, and general upkeep',
    accountRole: null,
  },
  {
    accountNumber: '61600',
    name: 'Cleaning & Janitorial',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Cleaning services, janitorial supplies, and sanitation',
    accountRole: null,
  },
  {
    accountNumber: '61700',
    name: 'Security Services',
    type: 'EXPENSE',
    subType: 'Facilities Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '61000',
    isActive: true,
    description: 'Security guards, alarm monitoring, camera systems, and access control',
    accountRole: null,
  },

  // ── Technology Expenses ─────────────────────────────────────────
  {
    accountNumber: '62000',
    name: 'Technology Expenses',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all IT, software, and technology costs',
    accountRole: null,
  },
  {
    accountNumber: '62100',
    name: 'Software Subscriptions',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '62000',
    isActive: true,
    description: 'SaaS subscriptions, cloud services, and recurring software fees',
    accountRole: null,
  },
  {
    accountNumber: '62200',
    name: 'POS System Fees',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '62000',
    isActive: true,
    description: 'Monthly POS platform fees, terminal licenses, and support',
    accountRole: null,
  },
  {
    accountNumber: '62300',
    name: 'Payment Processing Fees',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '62000',
    isActive: true,
    description: 'Credit/debit card transaction fees, gateway fees, and processor charges',
    accountRole: 'PAYMENT_PROCESSING_FEES',
  },
  {
    accountNumber: '62400',
    name: 'IT Support & Services',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '62000',
    isActive: true,
    description: 'Outsourced IT support, help desk, network management, and consulting',
    accountRole: null,
  },
  {
    accountNumber: '62500',
    name: 'Internet & Telecom',
    type: 'EXPENSE',
    subType: 'Technology Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '62000',
    isActive: true,
    description: 'Internet service, phone lines, mobile plans, and telecom',
    accountRole: null,
  },

  // ── Marketing Expenses ──────────────────────────────────────────
  {
    accountNumber: '63000',
    name: 'Marketing Expenses',
    type: 'EXPENSE',
    subType: 'Marketing Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for all advertising, promotion, and brand costs',
    accountRole: null,
  },
  {
    accountNumber: '63100',
    name: 'Advertising',
    type: 'EXPENSE',
    subType: 'Marketing Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '63000',
    isActive: true,
    description: 'Print, digital, radio, TV, and social media advertising spend',
    accountRole: null,
  },
  {
    accountNumber: '63200',
    name: 'Promotions & Campaigns',
    type: 'EXPENSE',
    subType: 'Marketing Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '63000',
    isActive: true,
    description: 'Cost of promotional campaigns, events, and seasonal marketing',
    accountRole: null,
  },
  {
    accountNumber: '63300',
    name: 'Website & SEO',
    type: 'EXPENSE',
    subType: 'Marketing Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '63000',
    isActive: true,
    description: 'Website hosting, development, maintenance, and SEO services',
    accountRole: null,
  },
  {
    accountNumber: '63400',
    name: 'Loyalty Program Costs',
    type: 'EXPENSE',
    subType: 'Marketing Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '63000',
    isActive: true,
    description: 'Cost of loyalty rewards, points redemptions, and loyalty platform fees',
    accountRole: null,
  },

  // ── Administrative Expenses ─────────────────────────────────────
  {
    accountNumber: '64000',
    name: 'Administrative Expenses',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for general and administrative overhead costs',
    accountRole: null,
  },
  {
    accountNumber: '64100',
    name: 'Office Supplies',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '64000',
    isActive: true,
    description: 'Paper, toner, pens, receipt rolls, and general office supplies',
    accountRole: null,
  },
  {
    accountNumber: '64200',
    name: 'Legal Fees',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '64000',
    isActive: true,
    description: 'Attorney fees, legal consultations, contracts, and compliance',
    accountRole: null,
  },
  {
    accountNumber: '64300',
    name: 'Accounting & Bookkeeping Fees',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '64000',
    isActive: true,
    description: 'CPA, bookkeeping, tax preparation, and audit services',
    accountRole: null,
  },
  {
    accountNumber: '64400',
    name: 'Bank Service Charges',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '64000',
    isActive: true,
    description: 'Monthly bank fees, wire transfer fees, and account maintenance charges',
    accountRole: null,
  },
  {
    accountNumber: '64500',
    name: 'Licenses & Permits',
    type: 'EXPENSE',
    subType: 'Administrative Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '64000',
    isActive: true,
    description: 'Business licenses, health permits, liquor licenses, and regulatory fees',
    accountRole: null,
  },

  // ── Industry-Specific Expenses ──────────────────────────────────
  {
    accountNumber: '65000',
    name: 'Industry-Specific Expenses',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for industry-specific operational costs (golf, marina, hospitality)',
    accountRole: null,
  },
  {
    accountNumber: '65100',
    name: 'Course Maintenance',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Golf course turf care, mowing, aeration, and course upkeep',
    accountRole: null,
  },
  {
    accountNumber: '65200',
    name: 'Grounds Crew',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Grounds maintenance labor (separate from general payroll for tracking)',
    accountRole: null,
  },
  {
    accountNumber: '65300',
    name: 'Chemicals & Fertilizer',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Pesticides, herbicides, fertilizer, and turf treatment chemicals',
    accountRole: null,
  },
  {
    accountNumber: '65400',
    name: 'Marina Operations',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'General marina operating costs including fuel, pumping, and supplies',
    accountRole: null,
  },
  {
    accountNumber: '65500',
    name: 'Dock Maintenance',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Dock repairs, piling maintenance, and slip infrastructure upkeep',
    accountRole: null,
  },
  {
    accountNumber: '65600',
    name: 'Housekeeping',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Room cleaning, turnover, linens, amenities, and housekeeping supplies',
    accountRole: null,
  },
  {
    accountNumber: '65700',
    name: 'Laundry Services',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Commercial laundry, dry cleaning, linen rental, and uniform cleaning',
    accountRole: null,
  },
  {
    accountNumber: '65800',
    name: 'Vehicle & Equipment Fuel',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Fuel for company vehicles, golf carts, mowers, and boats',
    accountRole: null,
  },
  {
    accountNumber: '65900',
    name: 'Equipment Repairs',
    type: 'EXPENSE',
    subType: 'Industry Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '65000',
    isActive: true,
    description: 'Repair and servicing of specialized equipment (kitchen, marine, course)',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // OTHER INCOME / EXPENSE (80000–82999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '80000',
    name: 'Other Income',
    type: 'OTHER_INCOME',
    subType: 'Other Income',
    normalBalance: 'CREDIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for non-operating income (interest, gains)',
    accountRole: null,
  },
  {
    accountNumber: '80100',
    name: 'Interest Income',
    type: 'OTHER_INCOME',
    subType: 'Other Income',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '80000',
    isActive: true,
    description: 'Interest earned on bank accounts, money market, or investments',
    accountRole: 'INTEREST_INCOME',
  },
  {
    accountNumber: '80200',
    name: 'Gain on Sale of Assets',
    type: 'OTHER_INCOME',
    subType: 'Other Income',
    normalBalance: 'CREDIT',
    isControl: false,
    parentAccountNumber: '80000',
    isActive: true,
    description: 'Gain realized from disposal of fixed assets above book value',
    accountRole: null,
  },

  // ── Other Expenses ──────────────────────────────────────────────
  {
    accountNumber: '81000',
    name: 'Other Expenses',
    type: 'OTHER_EXPENSE',
    subType: 'Other Expense',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for non-operating expenses (interest, depreciation, amortization)',
    accountRole: null,
  },
  {
    accountNumber: '81100',
    name: 'Interest Expense',
    type: 'OTHER_EXPENSE',
    subType: 'Other Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '81000',
    isActive: true,
    description: 'Interest paid on loans, lines of credit, and financed equipment',
    accountRole: 'INTEREST_EXPENSE',
  },
  {
    accountNumber: '81200',
    name: 'Depreciation Expense',
    type: 'OTHER_EXPENSE',
    subType: 'Other Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '81000',
    isActive: true,
    description: 'Periodic depreciation of tangible fixed assets',
    accountRole: 'DEPRECIATION_EXPENSE',
  },
  {
    accountNumber: '81300',
    name: 'Amortization Expense',
    type: 'OTHER_EXPENSE',
    subType: 'Other Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '81000',
    isActive: true,
    description: 'Periodic amortization of intangible assets and leasehold improvements',
    accountRole: null,
  },
  {
    accountNumber: '81400',
    name: 'Other Miscellaneous Expense',
    type: 'OTHER_EXPENSE',
    subType: 'Other Expense',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '81000',
    isActive: true,
    description: 'Non-recurring and miscellaneous non-operating expenses',
    accountRole: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // SYSTEM / STATISTICAL (90000–99999)
  // ═══════════════════════════════════════════════════════════════════

  {
    accountNumber: '99000',
    name: 'System Accounts',
    type: 'EXPENSE',
    subType: 'System',
    normalBalance: 'DEBIT',
    isControl: true,
    parentAccountNumber: null,
    isActive: true,
    description: 'Control account for system-managed accounts (rounding, suspense)',
    accountRole: null,
  },
  {
    accountNumber: '99910',
    name: 'Rounding / Reconciliation Adjustments',
    type: 'EXPENSE',
    subType: 'System',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: '99000',
    isActive: true,
    description: 'Auto-posted penny rounding to balance journal entries within tolerance',
    accountRole: 'ROUNDING_RECONCILIATION',
  },
  {
    accountNumber: '99920',
    name: 'Suspense / Clearing Account',
    type: 'ASSET',
    subType: 'System',
    normalBalance: 'DEBIT',
    isControl: false,
    parentAccountNumber: null,
    isActive: true,
    description: 'Temporary holding account for unclassified transactions pending resolution',
    accountRole: 'SUSPENSE_CLEARING',
  },
];

// ── Validation helpers ──────────────────────────────────────────────

/** Verify parent-child integrity: every parentAccountNumber must exist in the dataset */
export function validateParentIntegrity(accounts: SeedAccount[]): string[] {
  const numbers = new Set(accounts.map((a) => a.accountNumber));
  const errors: string[] = [];
  for (const acct of accounts) {
    if (acct.parentAccountNumber && !numbers.has(acct.parentAccountNumber)) {
      errors.push(
        `Account ${acct.accountNumber} "${acct.name}" references parent ${acct.parentAccountNumber} which does not exist`,
      );
    }
  }
  return errors;
}

/** Verify no duplicate account numbers */
export function validateUniqueNumbers(accounts: SeedAccount[]): string[] {
  const seen = new Map<string, string>();
  const errors: string[] = [];
  for (const acct of accounts) {
    if (seen.has(acct.accountNumber)) {
      errors.push(
        `Duplicate account number ${acct.accountNumber}: "${seen.get(acct.accountNumber)}" and "${acct.name}"`,
      );
    }
    seen.set(acct.accountNumber, acct.name);
  }
  return errors;
}

/** Verify no duplicate account roles */
export function validateUniqueRoles(accounts: SeedAccount[]): string[] {
  const seen = new Map<string, string>();
  const errors: string[] = [];
  for (const acct of accounts) {
    if (acct.accountRole) {
      if (seen.has(acct.accountRole)) {
        errors.push(
          `Duplicate role ${acct.accountRole}: "${seen.get(acct.accountRole)}" and "${acct.name}"`,
        );
      }
      seen.set(acct.accountRole, acct.name);
    }
  }
  return errors;
}

/** Topologically sort accounts so parents are inserted before children */
export function topologicalSort(accounts: SeedAccount[]): SeedAccount[] {
  const byNumber = new Map(accounts.map((a) => [a.accountNumber, a]));
  const sorted: SeedAccount[] = [];
  const visited = new Set<string>();

  function visit(acct: SeedAccount) {
    if (visited.has(acct.accountNumber)) return;
    if (acct.parentAccountNumber) {
      const parent = byNumber.get(acct.parentAccountNumber);
      if (parent) visit(parent);
    }
    visited.add(acct.accountNumber);
    sorted.push(acct);
  }

  for (const acct of accounts) {
    visit(acct);
  }
  return sorted;
}
